"""add repo snapshots and code chunks

Revision ID: 3c8153201c7b
Revises: dfff9e42b411
Create Date: 2026-08-08 17:44:50.367141

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c8153201c7b"
down_revision: str | Sequence[str] | None = "dfff9e42b411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repo_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_owner", sa.String(length=255), nullable=False),
        sa.Column("repo_name", sa.String(length=255), nullable=False),
        sa.Column("sha", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_owner", "repo_name", "sha", name="uq_repo_snapshot"),
    )
    op.create_table(
        "code_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("chunk_type", sa.String(length=20), nullable=False),
        sa.Column("symbol", sa.String(length=255), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["repo_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_chunks_file_path"), "code_chunks", ["file_path"], unique=False)
    op.create_index(
        op.f("ix_code_chunks_snapshot_id"), "code_chunks", ["snapshot_id"], unique=False
    )
    op.create_index(op.f("ix_code_chunks_symbol"), "code_chunks", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_code_chunks_symbol"), table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_snapshot_id"), table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_file_path"), table_name="code_chunks")
    op.drop_table("code_chunks")
    op.drop_table("repo_snapshots")
    # ### end Alembic commands ###
