"""init webhook events and review runs

Revision ID: 7f997b7c8b7a
Revises:
Create Date: 2026-08-08 16:40:48.063361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f997b7c8b7a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.execute("CREATE EXTENSION IF NOT EXISTS vector")
  op.create_table(
    "review_runs",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("repo_owner", sa.String(length=255), nullable=False),
    sa.Column("repo_name", sa.String(length=255), nullable=False),
    sa.Column("pr_number", sa.Integer(), nullable=False),
    sa.Column("head_sha", sa.String(length=64), nullable=False),
    sa.Column("config_version", sa.String(length=50), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.Column("abstain_reason", sa.Text(), nullable=True),
    sa.Column("error", sa.Text(), nullable=True),
    sa.Column("github_review_id", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
      "repo_owner",
      "repo_name",
      "pr_number",
      "head_sha",
      "config_version",
      name="uq_review_run_identity",
    ),
  )
  op.create_index(op.f("ix_review_runs_status"), "review_runs", ["status"], unique=False)
  op.create_table(
    "webhook_events",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("delivery_id", sa.String(length=255), nullable=False),
    sa.Column("event", sa.String(length=100), nullable=False),
    sa.Column("action", sa.String(length=50), nullable=True),
    sa.Column("repository", sa.String(length=255), nullable=True),
    sa.Column("pr_number", sa.Integer(), nullable=True),
    sa.Column("payload", sa.JSON(), nullable=False),
    sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    op.f("ix_webhook_events_delivery_id"), "webhook_events", ["delivery_id"], unique=True
  )
  op.create_table(
    "review_comments",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("run_id", sa.Integer(), nullable=False),
    sa.Column("file_path", sa.String(length=500), nullable=False),
    sa.Column("line", sa.Integer(), nullable=False),
    sa.Column("severity", sa.String(length=20), nullable=False),
    sa.Column("category", sa.String(length=30), nullable=False),
    sa.Column("title", sa.String(length=200), nullable=False),
    sa.Column("body", sa.Text(), nullable=False),
    sa.Column("suggested_fix", sa.Text(), nullable=True),
    sa.Column("confidence", sa.Float(), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False),
    sa.Column("suppression_reason", sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(
      ["run_id"],
      ["review_runs.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_review_comments_run_id"), "review_comments", ["run_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_review_comments_run_id"), table_name="review_comments")
  op.drop_table("review_comments")
  op.drop_index(op.f("ix_webhook_events_delivery_id"), table_name="webhook_events")
  op.drop_table("webhook_events")
  op.drop_index(op.f("ix_review_runs_status"), table_name="review_runs")
  op.drop_table("review_runs")
  # ### end Alembic commands ###
